# Generated by Django 5.1.3 on 2024-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('only_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_at',
            field=models.DateField(),
        ),
    ]
