# Generated by Django 5.1.3 on 2024-11-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('only_course', '0003_rename_name_course_title_rename_name_lesson_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='expert',
            new_name='specialty',
        ),
    ]
